### ISSUE TITLE
Migrate CUBA dashboard-addon

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-dashboards#1]
See https://github.com/cuba-platform/dashboard-addon

- [x] Investigate the issue

Migrate:
- [x] Entities:
	- [x] Classes
	- [x] SQL scripts -> Liquibase changeset
	- [x] Views -> Fetch plans
	- [x] Messages (remove Title Case usages)
- [x] Model objects
- [x] Security roles
- [x] Beans
- [x] UI components: 
	 - [x] Components
	 - [x] Loaders
	 - [x] XSD schema
- [x] Screens:
	- [x] PersistentDashboardBrowse (migrate to new screen API)
	- [x] ColspanDialog (migrate to new screen API)
	- [x] CssLayoutCreationDialog (migrate to new screen API)
	- [x] ExpandDialog (migrate to new screen API)
	- [x] GridCreationDialog (migrate to new screen API)
	- [x] ResponsiveCreationDialog (migrate to new screen API)
	- [x] StyleDialog (migrate to new screen API)
	- [x] WeightDialog (migrate to new screen API)
	- [x] DashboardEdit (migrate to new screen API):
		- [x] PaletteFrame 
		- [x] CanvasFrame, CanvasEditorFrame
	- [x] DashboardFrame, WebDashboardFrame (migrate to new screen API)
	- [x] DashboardView (migrate to new screen API)
	- [x] WidgetEdit (migrate to new screen API)
	- [x] Parameter screens (migrate to new screen API):
		- [x] Browser 
		- [x] Editor
	- [x] WidgetTemplate screens (migrate to new screen API):
		- [x] Browser
		- [x] Editor
	- [x] WidgetTemplateGroup screens (migrate to new screen API):
		- [x] Browser 
		- [x] Editor
	- [x] Value frames (migrate to new screen API):
		- [x] EntitiesList
		- [x] Entity
		- [x] Simple
	- [x] DashboardGroup screens (migrate to new screen API):
		- [x] Browser
		- [x] Editor	
- [x] UI messages (remove Title Case usages)
- [x] Component factories
- [x] Layouts
- [x] Events
- [x] CSS Styles
- [x] README.md

**Comment by knstvk** [comment]
Use `dashboards / dshbrd` long/short project id.
