### ISSUE TITLE
Unable to change caption and  "Show widget caption" value  in Widget editor

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-dashboards#10]
#### Enviroment:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2824-211
IntelliJ version: IntelliJ IDEA 2021.1 (Community Edition)

#### TC:
1. Open [attached](https://github.com/Haulmont/jmix-dashboards/files/6421045/dashboards.zip) project -> load Gradle dependencies -> run app
2. Open Widget templates browser -> create
3. Set any widget type -> Set caption "Caption" in widget editor -> activate checkbox "Show caption" -> Ok -> Save template
4. Select added template -> edit -> customize -> inactivate checkbox and change caption to "Caption2" -> Ok -> Save
5. Select added template -> edit -> customize

#### AR:
checkbox is activated, caption has not been changed

#### ER:
all changes are saved

**Comment by Desire456** [comment]
Already fixed in https://github.com/Haulmont/jmix-dashboards/issues/8
