### ISSUE TITLE
Section 'General' is displayed incorrect in Widget editor when user has dashboards-admin role 

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-dashboards#11]
#### Enviroment:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2824-211
IntelliJ version: IntelliJ IDEA 2021.1 (Community Edition)

#### TC:
1. Open attached project -> load Gradle dependencies -> run app
2. Open Users browser -> create new one -> save -> add role 'dashboards-admin' and 'system-minimal' -> save
3. Logout and login as new user
4. Open Widget templates browser -> create
5. Choose any widget type

#### AR:
There is no fields in section 'General':
![image](https://user-images.githubusercontent.com/45730069/117011360-d16a3000-acfe-11eb-9595-d8cb9846c245.png)

#### ER:
user should see all fields as user with full-access role:
![image](https://user-images.githubusercontent.com/45730069/117011638-13937180-acff-11eb-83ea-005925aed14e.png)

[dashboards.zip](https://github.com/Haulmont/jmix-dashboards/files/6421417/dashboards.zip)

**Comment by Desire456** [comment]
Commit reference https://github.com/Haulmont/jmix-dashboards/commit/efadbf5d1beedf6364b938fe6efa2ff8151db458
