### ISSUE TITLE
Widget value has not been refreshing after button "Propagate" clicking in Dashboard editor

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-dashboards#17]
#### Enviroment:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2839-211
IntelliJ version: IntelliJ IDEA 2021.1 (Community Edition)

#### TC:
1. Open [attached](https://github.com/Haulmont/jmix-dashboards/files/6421417/dashboards.zip) project -> load Gradle dependencies -> run app
2. Open Dashboards browser -> create new one
3. Add Clock widget to dashboard -> select bean 'ClockAssistant' in 'Assistant bean name' combobox 
4. Wait several seconds -> click 'Propagate' button

#### AR:
timer value has not been refreshing

#### ER:
timer value has been refreshing

**Comment by Desire456** [comment]
Actually, that behavior is expected. To test _Propagate_ button's work you should open two screens simultaneously: editor screen and view screen (_Show_ button). And when you click _Propagate_ button you can see widget refreshing in view screen.

**Comment by owlet1997** [comment]
The scenario was reproduced, neither was widget:
![image](https://user-images.githubusercontent.com/45730069/119979452-09962300-bfcc-11eb-8ddf-8cea07b3d1bd.png)
