### ISSUE TITLE
Customize DeletePolicyException notifications on Widget template group deleting

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-dashboards#19]
#### Enviroment:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2839-211
IntelliJ version: IntelliJ IDEA 2021.1 (Community Edition)

#### TC:
1. Open [attached](https://github.com/Haulmont/jmix-dashboards/files/6421417/dashboards.zip) project -> load Gradle dependencies -> run app
2. Open Widget templates browser -> click Groups -> create new one -> save
3. Create new Widget template -> fill properties -> set added group -> save
4. Open Widget templates browser -> click Groups -> select added group -> click 'Remove' -> confirm

#### AR:
'Unexpected error' window has been appearing, but this error is quite expected
![image](https://user-images.githubusercontent.com/45730069/117152844-75211200-adcb-11eb-94a5-02036b12e8b4.png)

#### ER:
customized notification about error with including related element's names (optionally)

**Comment by Desire456** [comment]
Already fixed in https://github.com/Haulmont/jmix-dashboards/issues/18
