### ISSUE TITLE
No validation for unique dashboard code

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-dashboards#21]
#### Enviroment:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2839-211
IntelliJ version: IntelliJ IDEA 2021.1 (Community Edition)

#### TC:
1. Open  [attached](https://github.com/Haulmont/jmix-dashboards/files/6421417/dashboards.zip) project -> run app
2. Open Dashboard -> Dashboards -> Create new
3. Set name chartsw, code w -> Save
4. Create new -> Set name chartsw, code w -> Save

#### AR:
dashboard successfully created
![image](https://user-images.githubusercontent.com/45730069/117436056-99056480-af3f-11eb-91ab-06f7888d1b95.png)

#### ER:
according to [documentation](https://github.com/Haulmont/jmix-dashboards#411-dashboard-fields) dashboards should have unique codes so there should be notification about duplicate codes

**Comment by Desire456** [comment]
Commit reference https://github.com/Haulmont/jmix-dashboards/commit/5cc49121d72cc774a15d8a92ef3c9c210bfad883

**Comment by Desire456** [comment]
For QA: don't test it on hsqldb
