### ISSUE TITLE
Unhandled exception after incorrect dashboard file importing

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-dashboards#23]
#### Enviroment:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2839-211
IntelliJ version: IntelliJ IDEA 2021.1 (Community Edition)

#### TC:
1. Open  [attached](https://github.com/Haulmont/jmix-dashboards/files/6421417/dashboards.zip) project -> run app
2. Open Dashboard -> Dashboards -> Create new
3. Click 'Import' -> choose any non-JSON file

#### AR:
![image](https://user-images.githubusercontent.com/45730069/117442352-b2aaaa00-af47-11eb-9172-97fc397cb451.png)

#### ER:
notification about incorrect file format

**Comment by gorbunkov** [comment]
@Desire456 Check uploaded file extension
