### ISSUE TITLE
Widget is not refreshed in ResponsiveGridLayout

### ISSUE THREAD

**Issue by m-orlova** [Haulmont/jmix-dashboards#28]
Project: [widget-not-refreshed.zip](https://github.com/Haulmont/jmix-dashboards/files/7987343/widget-not-refreshed.zip)
Jmix version: 1.1.3

**Steps to reproduce:**
1. Open menu: Dashboard -> Dashboards
2. Click the "Create" button on the Dashboards browser
3. Specify the "Name",  "Code" and "Refresh period (sec)" fields. The refresh period should be greater than 0. 
4. Add a responsive layout to the root layout (by dragging and dropping the "Responsive layout" from the "Layouts" block)
5. Add the "Random Id" widget to the responsive layout (by dragging and dropping the "Random Id" widget from the "Widgets" block).
6. Specify a name in the opened widget editor and click "OK".
7. Save a dashboard
8. Select a created dashboard on the Dashboards browser and click the "Show" button
**ER:** The string value on the widget is updated. The period of the update is equal to the value of the "Refresh period (sec)" field.
**AR:** String value is not updated on the widget.

Implemented widget (RandomIdWidget class) is refreshable and is updated in other types of layouts.

**Comment by Afanasevaa36** [comment]
Jmix version: 1.1.999-SNAPSHOT - verified
Jmix version: 1.2.0-SNAPSHOT - verified
