### ISSUE TITLE
Widget is removed after moving in the tree 

### ISSUE THREAD

**Issue by m-orlova** [Haulmont/jmix-dashboards#29]
Project: [widget-disappears-after-moving.zip](https://github.com/Haulmont/jmix-dashboards/files/7987585/widget-disappears-after-moving.zip)
Jmix version: 1.1.3

**Steps to reproduce:**
1. Open menu: Dashboard -> Dashboards
2. Click the "Create" button on the Dashboards browser
3. Specify  "Name" and "Code". 
4. Add a responsive layout to the root layout (by dragging and dropping the "Responsive layout" from the "Layouts" block)
5. Add two widgets to the responsive layout (by dragging and dropping widgets from the "Widgets" block).
6. Change widgets order in the layouts tree. For example, move up the second widget.
**ER:** The second widget appears before the first widget.
**AR:** The second widget is removed.

**Comment by Afanasevaa36** [comment]
Jmix version: 1.1.999-SNAPSHOT - verified
Jmix version: 1.2.0-SNAPSHOT - verified
