### ISSUE TITLE
Error message if add a widget in the GridLayout instead of cell

### ISSUE THREAD

**Issue by m-orlova** [Haulmont/jmix-dashboards#30]
Project: [dashboard-sample.zip](https://github.com/Haulmont/jmix-dashboards/files/7987753/dashboard-sample.zip)
Jmix version: 1.1.3

**Steps to reproduce:**
1. Open menu: Dashboard -> Dashboards
2. Click the "Create" button on the Dashboards browser
3. Add a grid layout to the root layout (by dragging and dropping the "Grid layout" from the "Layouts" block)
4. Add any widget or layout directly to the grid layout, NOT in the grid layout cell.
**AR:** Exception is thrown and the following message is shown
![image](https://user-images.githubusercontent.com/71265042/152181300-deb3d043-9e58-45cd-8843-cbed3baff701.png).
**ER:** More descriptive message is shown

**Comment by Afanasevaa36** [comment]
Jmix version: 1.1.999-SNAPSHOT
Jmix Studio plugin version: 1.2.SNAPSHOT4085-213
The bug is still playing
![Screenshot_4](https://user-images.githubusercontent.com/95623805/154816333-75204efd-8e66-491b-8a5f-080776e4dad0.png)

**Comment by Flaurite** [comment]
@Afanasevaa36 Hi! The fix provided only for 1.2.0-SNAPSHOT. There is no created issue for 1.1.x version.

**Comment by Afanasevaa36** [comment]
Jmix version: 1.2.0-SNAPSHOT - verified
