### ISSUE TITLE
Tree is not updated after moving a widget from one layout to another on the canvas

### ISSUE THREAD

**Issue by m-orlova** [Haulmont/jmix-dashboards#31]
Project: [dashboard-sample.zip](https://github.com/Haulmont/jmix-dashboards/files/7987819/dashboard-sample.zip)
Jmix version: 1.1.3

**Steps to reproduce:**
1. Open menu: Dashboard -> Dashboards
2. Click the "Create" button on the Dashboards browser
4. Add a vertical layout to the root layout
5. Add a widget to the vertical layout
6. Add a responsive layout to the root layout
7. Move widget from vertical layout to responsive layout on the canvas
**ER:** Widget is moved to the responsive layout and layout tree is updated. Widget is shown in the responsive layout in the tree.
**AR:** Widget is moved to the responsive layout but in the tree it is still shown in the vertical layout.

![image](https://user-images.githubusercontent.com/71265042/152185778-0c5ceeba-bca7-41e1-b50a-2b1dca8b2a0c.png)

**Comment by Afanasevaa36** [comment]
Jmix version: 1.1.999-SNAPSHOT - verified
Jmix version: 1.2.0-SNAPSHOT - verified
