### ISSUE TITLE
Migrate CUBA dashboard-addon (phase 2)

### ISSUE THREAD

**Issue by m-orlova** [Haulmont/jmix-dashboards#4]
Phase 1: #1

- [x] Finish Responsive layout implementation
- [x] Finish dashboard component implementation
- [x] Check and correct Javadocs
- [x] Check and fix Spotbugs
- [x] Translations
- [x] Check serialization (EntityEntry field)
- [x] Include add-on in jmix-all, jmix-bom

**Comment by owlet1997** [comment]
#### Checked cases:
1. Create/Edit/Remove dashboard groups  
2. Create/Edit/Remove widget template groups 
3. Adding layout to dashboards:
 - vertical
 - horizontal
 - grid
 - css
 - responsive
 4. Export Dashboard as JSON
 5. Import Dashboard (positive/negative cases)
 6. Create Widget template
 7. Create/Edit/Remove widget templates
 8. Create/Edit/Remove/View dashboards:
 - add widgets
 - add widget templates
 9. Check permissions with dashboard-admin role 
 10. Check user's permissions with dashboard-view role
 11. Check user's permissions with dashboard-browse role
 12. Create screen with dashboard using 'jsonPath'
