### ISSUE TITLE
Unable to edit/delete widget parameter value 

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-dashboards#8]
#### Enviroment:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2778-211
IntelliJ version: IntelliJ IDEA 2021.1 (Community Edition)

#### TC:
1. Open [attached](https://app.zenhub.com/files/342163483/67b277f3-e966-4d47-a5f3-4bba18c94f53/download) project -> run app
2. Open Dashboard -> Widget templates
3. Click "Create" button on Widget template browser
4. Select a widget "Lookup"  in combo box
5. In opened Widget editor: fill Caption, Widget Id and add any parameter in "Widget parameters" group
6. Click "Ok" to save widget
7. Selecn createc template -> Edit -> Click "Customize" button in Widget template editor
8. Remove parameter or edit parameter value -> save
9. Reopen template -> customize

#### AR: 
Parameter still exists (if was deleted) or parameter  value changes have not been saved in the table

**Comment by Desire456** [comment]
Commit reference https://github.com/Haulmont/jmix-dashboards/commit/4bd5b3ca5d25493b1fbede913c712cdb998061f6
